/**
 * Read-only access to staging-orders-v2 and staging-shipments for
 * verification.
 *
 * SCHEMA — CONFIRMED (2026-07-17) via a one-off probe (order #9699) plus
 * follow-up origin_index / PK queries against a live order on US staging.
 * The real shape differs from the original guess in three ways:
 *
 *   1. The partition key on both tables is an opaque internal order UUID
 *      generated by the OMS/fulfilment system — NOT the Shopify order id or
 *      name. There is no direct way to compute it from a Shopify order.
 *   2. staging-orders-v2 has a GSI `origin_index` (HASH=origin) — the real
 *      correlation key. For Shopify-sourced orders, origin has the form
 *      "{STORE}#SHOPIFY_ECOM#{shopifyOrderIdTail}" (e.g.
 *      "US#SHOPIFY_ECOM#7772060320017" for order #9699 / gid tail
 *      7772060320017). staging-shipments has NO origin_index — it shares
 *      the same PK as staging-orders-v2 for a given order, so the PK is
 *      resolved via staging-orders-v2 first, then used to Query
 *      staging-shipments directly.
 *   3. Both tables store one row per unit (SK prefix "ITEM#<uuid>"), not a
 *      nested `items` list — confirming the "Shopify merges duplicate line
 *      items; DynamoDB does not" design note also holds for staging-orders-v2,
 *      not just staging-shipments. Allocation state is NOT on the ITEM# row
 *      itself: an ITEM# row carries `status` (OPEN/ALLOCATED/FULFILLED/
 *      UNDELIVERABLE/...) and, once allocated, a `shipmentId` pointing at a
 *      sibling `SHIPMENT#<shipmentId>` row whose `allocatedStore` attribute
 *      holds the plain store number (e.g. "100" — not "BRANCH_100").
 *
 * staging-orders-v2 row shapes (by SK prefix):
 *   "ORDER"            - order summary (shopifyExternalOrderId, status, totals)
 *   "ADDRESS#BILLING" / "ADDRESS#SHIPPING"
 *   "ITEM#<uuid>"      - one row per unit (sku, status, shopifyLineItemId, totals)
 *   "TRANSACTION#<ts>" - event log (CREATE_ORDER, etc.)
 *
 * staging-shipments row shapes (by SK prefix):
 *   "ITEM#<uuid>"        - one row per unit (sku, status, rejectedStores, shipmentId once allocated).
 *                          After undeliverable cleanup the row is NOT deleted - status flips
 *                          UNDELIVERABLE -> REMOVED (confirmed live, ~40-60s after the refund).
 *   "SHIPMENT#<id>"      - allocatedStore, carrier, status, packages, shippingAddress
 *   "TRANSACTION#<ts>"   - event log (SHIPMENT_CREATE, REALLOCATION, SHIPMENT_ITEM_REMOVED, etc.)
 */

import { QueryCommand } from "@aws-sdk/lib-dynamodb";
import type { DynamoClient } from "../clients/dynamo";
import type { RegressionConfig, Store } from "../config";

const ORIGIN_INDEX = "origin_index";
export const UNDELIVERABLE = "UNDELIVERABLE";
/**
 * Terminal status an ITEM# row carries after undeliverable cleanup. The row
 * is NOT deleted — confirmed live (orders #9706/#9707): staging-shipments
 * flips the item's `status` from UNDELIVERABLE to REMOVED roughly 40-60s
 * after the Shopify refund lands, and a SHIPMENT_ITEM_REMOVED transaction
 * row is appended. assertItemsRemoved checks for this status, not row
 * absence.
 */
export const REMOVED = "REMOVED";

export interface ShipmentItem {
  sku: string;
  store: string | null; // plain store number, "UNDELIVERABLE", or null (not yet allocated)
  status: string;
  rejectedStores: string[];
  shipmentItemId: string; // the ITEM#<uuid> sort key, prefix retained verbatim
  shipmentId: string | null; // bare uuid, null until the item is allocated to a shipment
  raw: Record<string, unknown>;
}

/**
 * The `SHIPMENT#` row itself (TAA-35 scope addition, 2026-08-21) — fulfilment-
 * relevant fields alongside the `allocatedStore` this reader already
 * surfaced. `trackingNumber` is the fulfilment outcome and lives only here:
 * the fulfil endpoint's 200 body carries `label_url`/`label_dimensions` and
 * no tracking number at all (confirmed live, orders #9922/#9923). `status`
 * is what a pre-fulfil guard reads (TAA-36); `carrier`/`pendingAction` are
 * cheap context for TAA-37's assertions. No polling here — the row lags a
 * fulfil call by ~6-9s (measured live, TAA-41 — see CLAUDE.md; supersedes
 * the earlier ~30s estimate); waiting for it to settle is TAA-36's job.
 */
export interface ShipmentSummary {
  shipmentId: string; // bare uuid, the SHIPMENT# sort key with the prefix stripped
  allocatedStore: string | null;
  status: string | null;
  trackingNumber: string | null;
  carrier: string | null;
  pendingAction: string | null;
  raw: Record<string, unknown>;
}

export interface AllocationSummary {
  totalUnits: number;
  byStore: Record<string, string[]>; // store -> [sku, ...] one entry per unit
  skuUnits: Record<string, number>;
  unallocated: number;
  undeliverableKey: string;
}

function originFor(store: Store, orderIdTail: string): string {
  return `${store}#SHOPIFY_ECOM#${orderIdTail}`;
}

/**
 * SKU -> total quantity from a set of staging-orders-v2 rows (one ITEM# row
 * per unit). Pure — offline-testable, and lets the composite poll (TAA-14
 * Phase A step 3) derive this from rows it already fetched instead of
 * re-querying.
 */
export function orderSkuQuantitiesFromRows(rows: Record<string, unknown>[]): Record<string, number> {
  const out: Record<string, number> = {};
  for (const row of rows) {
    if (!String(row.SK ?? "").startsWith("ITEM#")) {
      continue;
    }
    const sku = String(row.sku ?? "");
    if (sku) {
      out[sku] = (out[sku] ?? 0) + 1;
    }
  }
  return out;
}

/**
 * The shared internal order UUID (PK) from a set of staging-orders-v2 rows,
 * or null if the order hasn't landed at all. Pure — see
 * orderSkuQuantitiesFromRows for why this is split out.
 */
export function orderPkFromRows(rows: Record<string, unknown>[]): string | null {
  if (rows.length === 0) {
    return null;
  }
  const orderRow = rows.find((row) => row.SK === "ORDER");
  return String((orderRow ?? rows[0]).PK);
}

/**
 * SHIPMENT# rows -> ShipmentSummary[]. Pure — offline-testable, and lets
 * getShipmentsByPk and getShipmentItemsByPk derive their views from the same
 * fetched rows instead of each re-querying staging-shipments.
 */
export function shipmentSummariesFromRows(rows: Record<string, unknown>[]): ShipmentSummary[] {
  const summaries: ShipmentSummary[] = [];
  for (const row of rows) {
    const sk = String(row.SK ?? "");
    if (!sk.startsWith("SHIPMENT#")) {
      continue;
    }
    summaries.push({
      shipmentId: sk.slice("SHIPMENT#".length),
      allocatedStore: row.allocatedStore ? String(row.allocatedStore) : null,
      status: row.status ? String(row.status) : null,
      trackingNumber: row.trackingNumber ? String(row.trackingNumber) : null,
      carrier: row.carrier ? String(row.carrier) : null,
      pendingAction: row.pendingAction ? String(row.pendingAction) : null,
      raw: row,
    });
  }
  return summaries;
}

/**
 * Groups a shipment's items by the shipmentId they were allocated to — the
 * shape a fulfilment payload is built from (TAA-35). Items not yet
 * allocated (shipmentId === null) carry no shipment to group under and are
 * excluded. Pure — offline-testable.
 */
export function groupItemsByShipment(items: ShipmentItem[]): Map<string, ShipmentItem[]> {
  const grouped = new Map<string, ShipmentItem[]>();
  for (const item of items) {
    if (item.shipmentId === null) {
      continue;
    }
    const group = grouped.get(item.shipmentId);
    if (group) {
      group.push(item);
    } else {
      grouped.set(item.shipmentId, [item]);
    }
  }
  return grouped;
}

export class DynamoReader {
  constructor(
    private readonly dynamo: DynamoClient,
    private readonly config: RegressionConfig,
  ) {}

  /** All staging-orders-v2 rows for an order, found via the origin_index GSI. Empty = not landed yet. */
  async getOrderRows(store: Store, orderIdTail: string): Promise<Record<string, unknown>[]> {
    const result = await this.dynamo.doc.send(
      new QueryCommand({
        TableName: this.config.ordersTable,
        IndexName: ORIGIN_INDEX,
        KeyConditionExpression: "origin = :origin",
        ExpressionAttributeValues: { ":origin": originFor(store, orderIdTail) },
      }),
    );
    return result.Items ?? [];
  }

  /** SKU -> total quantity for the order as recorded in staging-orders-v2 (one ITEM# row per unit). */
  async getOrderSkuQuantities(store: Store, orderIdTail: string): Promise<Record<string, number>> {
    const rows = await this.getOrderRows(store, orderIdTail);
    return orderSkuQuantitiesFromRows(rows);
  }

  /** The shared internal order UUID (PK) used by both tables, resolved via staging-orders-v2. Null if not landed yet. */
  async getOrderPk(store: Store, orderIdTail: string): Promise<string | null> {
    const rows = await this.getOrderRows(store, orderIdTail);
    return orderPkFromRows(rows);
  }

  /**
   * ITEM# rows for an order from staging-shipments, normalized with the
   * allocated store resolved from the sibling SHIPMENT# row. One entry per
   * unit. Empty = shipments not created yet OR the order hasn't landed in
   * staging-orders-v2 at all (so no PK to query with) — callers distinguish
   * by pipeline stage.
   */
  async getShipmentItems(store: Store, orderIdTail: string): Promise<ShipmentItem[]> {
    const pk = await this.getOrderPk(store, orderIdTail);
    if (!pk) {
      return [];
    }
    return this.getShipmentItemsByPk(pk);
  }

  /**
   * Same as getShipmentItems, but for a PK already resolved by the caller —
   * lets the composite orders_table+allocation poll (TAA-14 Phase A step 3)
   * resolve the PK once from rows it already fetched, instead of every
   * allocation tick re-querying staging-orders-v2 just to re-derive it.
   */
  async getShipmentItemsByPk(pk: string): Promise<ShipmentItem[]> {
    const rows = await this.queryShipmentRows(pk);

    const shipmentsById = new Map<string, Record<string, unknown>>();
    for (const row of rows) {
      const sk = String(row.SK ?? "");
      if (sk.startsWith("SHIPMENT#")) {
        shipmentsById.set(sk.slice("SHIPMENT#".length), row);
      }
    }

    const items: ShipmentItem[] = [];
    for (const row of rows) {
      const sk = String(row.SK ?? "");
      if (!sk.startsWith("ITEM#")) {
        continue; // shipment-level or transaction row, not an item row
      }
      const status = String(row.status ?? "");
      const shipmentId = row.shipmentId ? String(row.shipmentId) : null;
      let allocatedStore: string | null = null;
      if (status === UNDELIVERABLE) {
        allocatedStore = UNDELIVERABLE;
      } else if (shipmentId) {
        const shipment = shipmentsById.get(shipmentId);
        const value = shipment?.allocatedStore;
        allocatedStore = value ? String(value) : null;
      }
      items.push({
        sku: String(row.sku ?? ""),
        store: allocatedStore,
        status,
        rejectedStores: (row.rejectedStores as string[] | undefined) ?? [],
        shipmentItemId: sk,
        shipmentId,
        raw: row,
      });
    }
    return items;
  }

  /**
   * SHIPMENT# rows for an order, for a PK already resolved by the caller —
   * same shape of call as getShipmentItemsByPk (TAA-35 scope addition,
   * 2026-08-21). The row is already fetched by getShipmentItemsByPk on every
   * run; this is a separate entry point for callers that only need the
   * shipment-level fields (status/trackingNumber/carrier/pendingAction),
   * not the per-item view.
   */
  async getShipmentsByPk(pk: string): Promise<ShipmentSummary[]> {
    const rows = await this.queryShipmentRows(pk);
    return shipmentSummariesFromRows(rows);
  }

  private async queryShipmentRows(pk: string): Promise<Record<string, unknown>[]> {
    const result = await this.dynamo.doc.send(
      new QueryCommand({
        TableName: this.config.shipmentsTable,
        KeyConditionExpression: "PK = :pk",
        ExpressionAttributeValues: { ":pk": pk },
      }),
    );
    return result.Items ?? [];
  }
}

/** Summarizes normalized shipment items for assertions. Pure (no AWS access) so it's offline-testable. */
export function allocationSummary(items: ShipmentItem[]): AllocationSummary {
  const byStore: Record<string, string[]> = {};
  const skuUnits: Record<string, number> = {};
  let unallocated = 0;
  for (const item of items) {
    let store = item.store;
    if (store === null || store === "") {
      unallocated += 1;
      store = "(unallocated)";
    }
    byStore[store] = byStore[store] ?? [];
    byStore[store].push(item.sku);
    skuUnits[item.sku] = (skuUnits[item.sku] ?? 0) + 1;
  }
  return {
    totalUnits: items.length,
    byStore,
    skuUnits,
    unallocated,
    undeliverableKey: UNDELIVERABLE,
  };
}
