/**
 * Read-only access to staging-orders-v2 and staging-shipments for
 * verification. Ports regression/readers/dynamo_reader.py.
 *
 * SCHEMA — CONFIRMED (2026-07-17) via `python -m regression.schema_probe
 * --order 9699` plus follow-up origin_index / PK queries against a live
 * order placed on US staging. This deviates from the original guess in
 * dynamo_reader.py in three ways:
 *
 *   1. The partition key on both tables is an opaque internal order UUID
 *      generated by the OMS/fulfilment system — NOT the Shopify order id or
 *      name. There is no direct way to compute it from a Shopify order.
 *   2. staging-orders-v2 has a GSI `origin_index` (HASH=origin) — the real
 *      correlation key. For Shopify-sourced orders, origin has the form
 *      "{STORE}#SHOPIFY_ECOM#{shopifyOrderIdTail}" (e.g.
 *      "US#SHOPIFY_ECOM#7772060320017" for order #9699 / gid tail
 *      7772060320017). staging-shipments has NO origin_index — it shares
 *      the same PK as staging-orders-v2 for a given order, so the PK is
 *      resolved via staging-orders-v2 first, then used to Query
 *      staging-shipments directly.
 *   3. Both tables store one row per unit (SK prefix "ITEM#<uuid>"), not a
 *      nested `items` list — confirming the "Shopify merges duplicate line
 *      items; DynamoDB does not" design note also holds for staging-orders-v2,
 *      not just staging-shipments. Allocation state is NOT on the ITEM# row
 *      itself: an ITEM# row carries `status` (OPEN/ALLOCATED/FULFILLED/
 *      UNDELIVERABLE/...) and, once allocated, a `shipmentId` pointing at a
 *      sibling `SHIPMENT#<shipmentId>` row whose `allocatedStore` attribute
 *      holds the plain store number (e.g. "100" — not "BRANCH_100").
 *
 * staging-orders-v2 row shapes (by SK prefix):
 *   "ORDER"            - order summary (shopifyExternalOrderId, status, totals)
 *   "ADDRESS#BILLING" / "ADDRESS#SHIPPING"
 *   "ITEM#<uuid>"      - one row per unit (sku, status, shopifyLineItemId, totals)
 *   "TRANSACTION#<ts>" - event log (CREATE_ORDER, etc.)
 *
 * staging-shipments row shapes (by SK prefix):
 *   "ITEM#<uuid>"        - one row per unit (sku, status, rejectedStores, shipmentId once allocated).
 *                          After undeliverable cleanup the row is NOT deleted - status flips
 *                          UNDELIVERABLE -> REMOVED (confirmed live, ~40-60s after the refund).
 *   "SHIPMENT#<id>"      - allocatedStore, carrier, status, packages, shippingAddress
 *   "TRANSACTION#<ts>"   - event log (SHIPMENT_CREATE, REALLOCATION, SHIPMENT_ITEM_REMOVED, etc.)
 */

import { QueryCommand } from "@aws-sdk/lib-dynamodb";
import type { DynamoClient } from "../clients/dynamo";
import type { RegressionConfig, Store } from "../config";

const ORIGIN_INDEX = "origin_index";
export const UNDELIVERABLE = "UNDELIVERABLE";
/**
 * Terminal status an ITEM# row carries after undeliverable cleanup. The row
 * is NOT deleted — confirmed live (orders #9706/#9707): staging-shipments
 * flips the item's `status` from UNDELIVERABLE to REMOVED roughly 40-60s
 * after the Shopify refund lands, and a SHIPMENT_ITEM_REMOVED transaction
 * row is appended. assertItemsRemoved checks for this status, not row
 * absence.
 */
export const REMOVED = "REMOVED";

export interface ShipmentItem {
  sku: string;
  store: string | null; // plain store number, "UNDELIVERABLE", or null (not yet allocated)
  status: string;
  rejectedStores: string[];
  raw: Record<string, unknown>;
}

export interface AllocationSummary {
  totalUnits: number;
  byStore: Record<string, string[]>; // store -> [sku, ...] one entry per unit
  skuUnits: Record<string, number>;
  unallocated: number;
  undeliverableKey: string;
}

function originFor(store: Store, orderIdTail: string): string {
  return `${store}#SHOPIFY_ECOM#${orderIdTail}`;
}

export class DynamoReader {
  constructor(
    private readonly dynamo: DynamoClient,
    private readonly config: RegressionConfig,
  ) {}

  /** All staging-orders-v2 rows for an order, found via the origin_index GSI. Empty = not landed yet. */
  async getOrderRows(store: Store, orderIdTail: string): Promise<Record<string, unknown>[]> {
    const result = await this.dynamo.doc.send(
      new QueryCommand({
        TableName: this.config.ordersTable,
        IndexName: ORIGIN_INDEX,
        KeyConditionExpression: "origin = :origin",
        ExpressionAttributeValues: { ":origin": originFor(store, orderIdTail) },
      }),
    );
    return result.Items ?? [];
  }

  /** SKU -> total quantity for the order as recorded in staging-orders-v2 (one ITEM# row per unit). */
  async getOrderSkuQuantities(store: Store, orderIdTail: string): Promise<Record<string, number>> {
    const rows = await this.getOrderRows(store, orderIdTail);
    const out: Record<string, number> = {};
    for (const row of rows) {
      if (!String(row.SK ?? "").startsWith("ITEM#")) {
        continue;
      }
      const sku = String(row.sku ?? "");
      if (sku) {
        out[sku] = (out[sku] ?? 0) + 1;
      }
    }
    return out;
  }

  /** The shared internal order UUID (PK) used by both tables, resolved via staging-orders-v2. Null if not landed yet. */
  async getOrderPk(store: Store, orderIdTail: string): Promise<string | null> {
    const rows = await this.getOrderRows(store, orderIdTail);
    if (rows.length === 0) {
      return null;
    }
    const orderRow = rows.find((row) => row.SK === "ORDER");
    return String((orderRow ?? rows[0]).PK);
  }

  /**
   * ITEM# rows for an order from staging-shipments, normalized with the
   * allocated store resolved from the sibling SHIPMENT# row. One entry per
   * unit. Empty = shipments not created yet OR the order hasn't landed in
   * staging-orders-v2 at all (so no PK to query with) — callers distinguish
   * by pipeline stage.
   */
  async getShipmentItems(store: Store, orderIdTail: string): Promise<ShipmentItem[]> {
    const pk = await this.getOrderPk(store, orderIdTail);
    if (!pk) {
      return [];
    }
    const result = await this.dynamo.doc.send(
      new QueryCommand({
        TableName: this.config.shipmentsTable,
        KeyConditionExpression: "PK = :pk",
        ExpressionAttributeValues: { ":pk": pk },
      }),
    );
    const rows = result.Items ?? [];

    const shipmentsById = new Map<string, Record<string, unknown>>();
    for (const row of rows) {
      const sk = String(row.SK ?? "");
      if (sk.startsWith("SHIPMENT#")) {
        shipmentsById.set(sk.slice("SHIPMENT#".length), row);
      }
    }

    const items: ShipmentItem[] = [];
    for (const row of rows) {
      const sk = String(row.SK ?? "");
      if (!sk.startsWith("ITEM#")) {
        continue; // shipment-level or transaction row, not an item row
      }
      const status = String(row.status ?? "");
      let allocatedStore: string | null = null;
      if (status === UNDELIVERABLE) {
        allocatedStore = UNDELIVERABLE;
      } else if (row.shipmentId) {
        const shipment = shipmentsById.get(String(row.shipmentId));
        const value = shipment?.allocatedStore;
        allocatedStore = value ? String(value) : null;
      }
      items.push({
        sku: String(row.sku ?? ""),
        store: allocatedStore,
        status,
        rejectedStores: (row.rejectedStores as string[] | undefined) ?? [],
        raw: row,
      });
    }
    return items;
  }
}

/** Summarizes normalized shipment items for assertions. Pure (no AWS access) so it's offline-testable. */
export function allocationSummary(items: ShipmentItem[]): AllocationSummary {
  const byStore: Record<string, string[]> = {};
  const skuUnits: Record<string, number> = {};
  let unallocated = 0;
  for (const item of items) {
    let store = item.store;
    if (store === null || store === "") {
      unallocated += 1;
      store = "(unallocated)";
    }
    byStore[store] = byStore[store] ?? [];
    byStore[store].push(item.sku);
    skuUnits[item.sku] = (skuUnits[item.sku] ?? 0) + 1;
  }
  return {
    totalUnits: items.length,
    byStore,
    skuUnits,
    unallocated,
    undeliverableKey: UNDELIVERABLE,
  };
}
