/**
 * Read-only access to staging-orders-v2 and staging-shipments for
 * verification.
 *
 * SCHEMA — CONFIRMED (2026-07-17) via a one-off probe (order #9699) plus
 * follow-up origin_index / PK queries against a live order on US staging.
 * The real shape differs from the original guess in three ways:
 *
 *   1. The partition key on both tables is an opaque internal order UUID
 *      generated by the OMS/fulfilment system — NOT the Shopify order id or
 *      name. There is no direct way to compute it from a Shopify order.
 *   2. staging-orders-v2 has a GSI `origin_index` (HASH=origin) — the real
 *      correlation key. For Shopify-sourced orders, origin has the form
 *      "{STORE}#SHOPIFY_ECOM#{shopifyOrderIdTail}" (e.g.
 *      "US#SHOPIFY_ECOM#7772060320017" for order #9699 / gid tail
 *      7772060320017). staging-shipments has NO origin_index — it shares
 *      the same PK as staging-orders-v2 for a given order, so the PK is
 *      resolved via staging-orders-v2 first, then used to Query
 *      staging-shipments directly.
 *   3. Both tables store one row per unit (SK prefix "ITEM#<uuid>"), not a
 *      nested `items` list — confirming the "Shopify merges duplicate line
 *      items; DynamoDB does not" design note also holds for staging-orders-v2,
 *      not just staging-shipments. Allocation state is NOT on the ITEM# row
 *      itself: an ITEM# row carries `status` (OPEN/ALLOCATED/FULFILLED/
 *      UNDELIVERABLE/...) and, once allocated, a `shipmentId` pointing at a
 *      sibling `SHIPMENT#<shipmentId>` row whose `allocatedStore` attribute
 *      holds the plain store number (e.g. "100" — not "BRANCH_100").
 *
 * staging-orders-v2 row shapes (by SK prefix):
 *   "ORDER"            - order summary (shopifyExternalOrderId, status, totals,
 *                        paymentMethod [singular, array], onHold [array of
 *                        reason strings, absent unless held] - see OrderRecord,
 *                        TAA-50)
 *   "ADDRESS#BILLING" / "ADDRESS#SHIPPING" - see AddressRow, TAA-50
 *   "ITEM#<uuid>"      - one row per unit (sku, status, shopifyLineItemId, totals,
 *                        deliveryMethod, clickCollectStore [CLICKCOLLECT rows
 *                        only], discountInfo - see OrderItemRow, TAA-50)
 *   "TRANSACTION#<ts>" - event log (CREATE_ORDER, etc.)
 *
 * staging-shipments row shapes (by SK prefix):
 *   "ITEM#<uuid>"        - one row per unit (sku, status, rejectedStores, shipmentId once allocated).
 *                          After undeliverable cleanup the row is NOT deleted - status flips
 *                          UNDELIVERABLE -> REMOVED (confirmed live, ~40-60s after the refund).
 *   "SHIPMENT#<id>"      - allocatedStore, carrier, status, packages, shippingAddress
 *   "TRANSACTION#<ts>"   - event log (SHIPMENT_CREATE, REALLOCATION, SHIPMENT_ITEM_REMOVED, etc.)
 */

import { QueryCommand } from "@aws-sdk/lib-dynamodb";
import type { DynamoClient } from "../clients/dynamo";
import type { RegressionConfig, Store } from "../config";

const ORIGIN_INDEX = "origin_index";
export const UNDELIVERABLE = "UNDELIVERABLE";
/**
 * Terminal status an ITEM# row carries after undeliverable cleanup. The row
 * is NOT deleted — confirmed live (orders #9706/#9707): staging-shipments
 * flips the item's `status` from UNDELIVERABLE to REMOVED roughly 40-60s
 * after the Shopify refund lands, and a SHIPMENT_ITEM_REMOVED transaction
 * row is appended. assertItemsRemoved checks for this status, not row
 * absence.
 */
export const REMOVED = "REMOVED";

export interface ShipmentItem {
  sku: string;
  store: string | null; // plain store number, "UNDELIVERABLE", or null (not yet allocated)
  status: string;
  rejectedStores: string[];
  shipmentItemId: string; // the ITEM#<uuid> sort key, prefix retained verbatim
  shipmentId: string | null; // bare uuid, null until the item is allocated to a shipment
  raw: Record<string, unknown>;
}

/**
 * The `SHIPMENT#` row itself (TAA-35 scope addition, 2026-08-21) — fulfilment-
 * relevant fields alongside the `allocatedStore` this reader already
 * surfaced. `trackingNumber` is the fulfilment outcome and lives only here:
 * the fulfil endpoint's 200 body carries `label_url`/`label_dimensions` and
 * no tracking number at all (confirmed live, orders #9922/#9923). `status`
 * is what a pre-fulfil guard reads (TAA-36); `carrier`/`pendingAction` are
 * cheap context for TAA-37's assertions. No polling here — the row lags a
 * fulfil call by ~6-9s (measured live, TAA-41 — see CLAUDE.md; supersedes
 * the earlier ~30s estimate); waiting for it to settle is TAA-36's job.
 */
export interface ShipmentSummary {
  shipmentId: string; // bare uuid, the SHIPMENT# sort key with the prefix stripped
  allocatedStore: string | null;
  status: string | null;
  trackingNumber: string | null;
  carrier: string | null;
  pendingAction: string | null;
  raw: Record<string, unknown>;
}

/**
 * A `TRANSACTION#` event-log row — the shared envelope BOTH `staging-
 * shipments` (TAA-31 slice G) and `staging-orders-v2` (TAA-48) use for their
 * append-only event history. Confirmed identical on both tables by live
 * capture (`ts/signoffs/TAA-48-slice-a.md`): every row on either table
 * carries `pk`/`sk`/`event`/`category`/`origin`/`idempotencyId` alongside
 * whatever event-specific payload it carries (`shipmentItemInfo`,
 * `itemChanges`, `paymentChanges`, `shipmentInfo`, ...) — `raw` is the
 * escape hatch for those. `shipmentItemInfo` is the per-item detail array
 * most `staging-shipments` events carry (e.g. `SHIPMENT_ITEM_REJECTED` rows
 * carry exactly one entry, keyed by `id`, the `ITEM#<uuid>` shipmentItemId);
 * events with no such array (e.g. bare `REALLOCATION` rows, and every
 * `staging-orders-v2` event) get `[]`, not `undefined`.
 *
 * `origin` means something DIFFERENT depending on which table the row came
 * from — on `staging-orders-v2` it's always the Shopify origin string
 * (`"US#SHOPIFY_ECOM#..."`); on `staging-shipments` it names the internal
 * system that emitted the event (`SHIPPING_SERVICE`, `DC_PACKING`,
 * `ORDERS_SERVICE`). Same field, two different meanings — read `raw` if the
 * distinction matters to a caller.
 */
export interface TransactionRow {
  pk: string; // the order's shared internal UUID, verbatim
  sk: string; // the TRANSACTION#<timestamp> sort key, verbatim
  event: string; // e.g. "CREATE_ORDER", "REFUND_ITEM", "SHIPMENT_REJECTED"
  category: string; // e.g. "CHARGE", "REFUND", "CREATION", "UPDATE", "REMOVAL", "ALLOCATION"
  origin: string; // see doc comment above — meaning depends on the source table
  idempotencyId: string;
  shipmentItemInfo: Record<string, unknown>[];
  raw: Record<string, unknown>;
}

/**
 * `TRANSACTION#` rows -> TransactionRow[], in the order given (a Query
 * against either table returns rows in ascending sort-key order, i.e.
 * already chronological — this does not re-sort). Pure — offline-testable,
 * same split as shipmentSummariesFromRows/ShipmentItem above, and
 * table-agnostic (TAA-48): reused for staging-orders-v2 rows below with no
 * change, since both tables share the same envelope (see TransactionRow).
 */
export function transactionRowsFromRows(rows: Record<string, unknown>[]): TransactionRow[] {
  const transactions: TransactionRow[] = [];
  for (const row of rows) {
    const sk = String(row.SK ?? "");
    if (!sk.startsWith("TRANSACTION#")) {
      continue;
    }
    transactions.push({
      pk: String(row.PK ?? ""),
      sk,
      event: String(row.event ?? ""),
      category: String(row.category ?? ""),
      origin: String(row.origin ?? ""),
      idempotencyId: String(row.idempotencyId ?? ""),
      shipmentItemInfo: Array.isArray(row.shipmentItemInfo) ? (row.shipmentItemInfo as Record<string, unknown>[]) : [],
      raw: row,
    });
  }
  return transactions;
}

/** Filter form for a chronological TransactionRow[] — e.g. isolate just the CREATE_ORDER row(s). Pure. */
export function transactionRowsByEvent(transactions: TransactionRow[], event: string): TransactionRow[] {
  return transactions.filter((t) => t.event === event);
}

export interface AllocationSummary {
  totalUnits: number;
  byStore: Record<string, string[]>; // store -> [sku, ...] one entry per unit
  skuUnits: Record<string, number>;
  unallocated: number;
  undeliverableKey: string;
}

function originFor(store: Store, orderIdTail: string): string {
  return `${store}#SHOPIFY_ECOM#${orderIdTail}`;
}

/**
 * SKU -> total quantity from a set of staging-orders-v2 rows (one ITEM# row
 * per unit). Pure — offline-testable, and lets the composite poll (TAA-14
 * Phase A step 3) derive this from rows it already fetched instead of
 * re-querying.
 */
export function orderSkuQuantitiesFromRows(rows: Record<string, unknown>[]): Record<string, number> {
  const out: Record<string, number> = {};
  for (const row of rows) {
    if (!String(row.SK ?? "").startsWith("ITEM#")) {
      continue;
    }
    const sku = String(row.sku ?? "");
    if (sku) {
      out[sku] = (out[sku] ?? 0) + 1;
    }
  }
  return out;
}

/**
 * The shared internal order UUID (PK) from a set of staging-orders-v2 rows,
 * or null if the order hasn't landed at all. Pure — see
 * orderSkuQuantitiesFromRows for why this is split out.
 */
export function orderPkFromRows(rows: Record<string, unknown>[]): string | null {
  if (rows.length === 0) {
    return null;
  }
  const orderRow = rows.find((row) => row.SK === "ORDER");
  return String((orderRow ?? rows[0]).PK);
}

export interface PaymentMethodEntry {
  method: string;
  amount: number;
}

/**
 * The ORDER row's hold/payment/totals surface (TAA-50) — one row per order.
 * `paymentMethod` is SINGULAR and an array of `{method, amount}` (there is
 * no `paymentMethods`), CONFIRMED across all 10 pre-existing fixtures plus
 * two more captured this ticket. `onHold` is an array of reason strings,
 * present only while the order is held — absent (not `[]`) on every
 * not-held fixture, normalized to `[]` here. Both reason strings this
 * ticket needed were confirmed live: `POTENTIAL_FRAUD`, from
 * `fulfillmentOrderHold(reason: HIGH_RISK_OF_FRAUD)` — the GraphQL enum
 * translates to this DynamoDB string, do not send `POTENTIAL_FRAUD` as
 * GraphQL input (order #9994, `US-hold-fraud-9994.json`); and
 * `OUTSTANDING_PAYMENT`, raised automatically by an order edit that adds an
 * unpaid item to an already-paid order — one of three triggers TAA-53
 * documented for the same mechanism, the other two being an unpaid order at
 * creation and an untargeted refund (order #9998,
 * `US-hold-outstanding-edit-9998.json`). `ccStore`/`finalPrice` are NOT on
 * this row — see OrderItemRow below for both. `currency` is present on
 * every fixture seen to date but kept nullable per the ticket's "if
 * present" — conservative, not evidence of an observed gap.
 */
export interface OrderRecord {
  status: string;
  onHold: string[];
  paymentMethod: PaymentMethodEntry[];
  subtotal: number;
  grandTotal: number;
  currency: string | null;
  customerId: string;
  raw: Record<string, unknown>;
}

/**
 * The ORDER row -> OrderRecord, or null if the order hasn't landed in
 * staging-orders-v2 yet (no ORDER row present). Pure — offline-testable,
 * same split as orderPkFromRows/orderSkuQuantitiesFromRows above.
 */
export function orderRecordFromRows(rows: Record<string, unknown>[]): OrderRecord | null {
  const row = rows.find((r) => r.SK === "ORDER");
  if (!row) {
    return null;
  }
  const paymentMethod = Array.isArray(row.paymentMethod)
    ? (row.paymentMethod as Record<string, unknown>[]).map((entry) => ({
        method: String(entry.method ?? ""),
        amount: Number(entry.amount ?? 0),
      }))
    : [];
  return {
    status: String(row.status ?? ""),
    onHold: Array.isArray(row.onHold) ? (row.onHold as unknown[]).map(String) : [],
    paymentMethod,
    subtotal: Number(row.subtotal ?? 0),
    grandTotal: Number(row.grandTotal ?? 0),
    currency: row.currency ? String(row.currency) : null,
    customerId: String(row.customerId ?? ""),
    raw: row,
  };
}

/**
 * An ADDRESS#SHIPPING or ADDRESS#BILLING row (TAA-50) — fields CONFIRMED
 * identical across every fixture under ts/fixtures/orders-v2/: street1,
 * phone, customerId, firstName, lastName, city, state, postalCode, country,
 * countryCode, origin, createdAt, updatedAt. `emailAddress` is
 * SHIPPING-only — null on every BILLING row observed, never absent on
 * SHIPPING.
 */
export interface AddressRow {
  type: "SHIPPING" | "BILLING";
  street1: string;
  phone: string;
  customerId: string;
  firstName: string;
  lastName: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  countryCode: string;
  origin: string;
  createdAt: number;
  updatedAt: number;
  emailAddress: string | null;
  raw: Record<string, unknown>;
}

/** ADDRESS# rows -> AddressRow[], in whatever order the Query returned. Pure — offline-testable. */
export function addressRowsFromRows(rows: Record<string, unknown>[]): AddressRow[] {
  const addresses: AddressRow[] = [];
  for (const row of rows) {
    const sk = String(row.SK ?? "");
    if (sk !== "ADDRESS#SHIPPING" && sk !== "ADDRESS#BILLING") {
      continue;
    }
    addresses.push({
      type: sk === "ADDRESS#SHIPPING" ? "SHIPPING" : "BILLING",
      street1: String(row.street1 ?? ""),
      phone: String(row.phone ?? ""),
      customerId: String(row.customerId ?? ""),
      firstName: String(row.firstName ?? ""),
      lastName: String(row.lastName ?? ""),
      city: String(row.city ?? ""),
      state: String(row.state ?? ""),
      postalCode: String(row.postalCode ?? ""),
      country: String(row.country ?? ""),
      countryCode: String(row.countryCode ?? ""),
      origin: String(row.origin ?? ""),
      createdAt: Number(row.createdAt ?? 0),
      updatedAt: Number(row.updatedAt ?? 0),
      emailAddress: row.emailAddress ? String(row.emailAddress) : null,
      raw: row,
    });
  }
  return addresses;
}

/**
 * An ITEM# row on staging-orders-v2 (TAA-50) — per-unit detail this table
 * already carried but no reader surfaced beyond a bare SKU count
 * (orderSkuQuantitiesFromRows). `deliveryMethod` observed "STANDARD" and
 * "CLICKCOLLECT"; `clickCollectStore` (plain store number string, e.g.
 * "251") is present ONLY on a CLICKCOLLECT row — live-captured via
 * draftOrderCreate's current (2025-10) `shippingLine.shippingRateHandle`
 * path (order #9997, `US-clickcollect-9997.json`); `cli-order.ts`'s
 * `--delivery pickup:` flag could not place the order itself, see the
 * sign-off. The SAME value is named `ccStore` on the CREATE_ORDER
 * TRANSACTION# row's `itemChanges.added[]` — envelope and row disagree on
 * the field's name, same class of drift as paymentMethod/
 * paymentChanges.payments.
 *
 * `finalPrice` does NOT exist on this row, or anywhere else in
 * staging-orders-v2 — chased live via a real orderEdit with a line-item
 * discount (order #9998, `US-hold-outstanding-edit-9998.json`): the
 * discount shows up only as `discountInfo: [{amount, code, type}]`, and
 * `grandTotal` already reflects the post-discount value (grandTotal 49 =
 * subtotal 50 - discountInfo[0].amount 1) — confirming TAA-53's edit-chain
 * finding that no separate discount/final-price field is ever emitted.
 * Deliberately left out of this interface; do not add it without a real
 * fixture (deferred to TAA-56).
 */
export interface OrderItemRow {
  sku: string;
  status: string;
  deliveryMethod: string;
  clickCollectStore: string | null;
  subtotal: number;
  grandTotal: number;
  discountInfo: Record<string, unknown>[];
  shopifyLineItemId: string;
  raw: Record<string, unknown>;
}

/** ITEM# rows on staging-orders-v2 -> OrderItemRow[]. Pure — offline-testable. */
export function orderItemRowsFromRows(rows: Record<string, unknown>[]): OrderItemRow[] {
  const items: OrderItemRow[] = [];
  for (const row of rows) {
    const sk = String(row.SK ?? "");
    if (!sk.startsWith("ITEM#")) {
      continue;
    }
    items.push({
      sku: String(row.sku ?? ""),
      status: String(row.status ?? ""),
      deliveryMethod: String(row.deliveryMethod ?? ""),
      clickCollectStore: row.clickCollectStore ? String(row.clickCollectStore) : null,
      subtotal: Number(row.subtotal ?? 0),
      grandTotal: Number(row.grandTotal ?? 0),
      discountInfo: Array.isArray(row.discountInfo) ? (row.discountInfo as Record<string, unknown>[]) : [],
      shopifyLineItemId: String(row.shopifyLineItemId ?? ""),
      raw: row,
    });
  }
  return items;
}

/**
 * SHIPMENT# rows -> ShipmentSummary[]. Pure — offline-testable, and lets
 * getShipmentsByPk and getShipmentItemsByPk derive their views from the same
 * fetched rows instead of each re-querying staging-shipments.
 */
export function shipmentSummariesFromRows(rows: Record<string, unknown>[]): ShipmentSummary[] {
  const summaries: ShipmentSummary[] = [];
  for (const row of rows) {
    const sk = String(row.SK ?? "");
    if (!sk.startsWith("SHIPMENT#")) {
      continue;
    }
    summaries.push({
      shipmentId: sk.slice("SHIPMENT#".length),
      allocatedStore: row.allocatedStore ? String(row.allocatedStore) : null,
      status: row.status ? String(row.status) : null,
      trackingNumber: row.trackingNumber ? String(row.trackingNumber) : null,
      carrier: row.carrier ? String(row.carrier) : null,
      pendingAction: row.pendingAction ? String(row.pendingAction) : null,
      raw: row,
    });
  }
  return summaries;
}

/**
 * Groups a shipment's items by the shipmentId they were allocated to — the
 * shape a fulfilment payload is built from (TAA-35). Items not yet
 * allocated (shipmentId === null) carry no shipment to group under and are
 * excluded. Pure — offline-testable.
 */
export function groupItemsByShipment(items: ShipmentItem[]): Map<string, ShipmentItem[]> {
  const grouped = new Map<string, ShipmentItem[]>();
  for (const item of items) {
    if (item.shipmentId === null) {
      continue;
    }
    const group = grouped.get(item.shipmentId);
    if (group) {
      group.push(item);
    } else {
      grouped.set(item.shipmentId, [item]);
    }
  }
  return grouped;
}

export class DynamoReader {
  constructor(
    private readonly dynamo: DynamoClient,
    private readonly config: RegressionConfig,
  ) {}

  /** All staging-orders-v2 rows for an order, found via the origin_index GSI. Empty = not landed yet. */
  async getOrderRows(store: Store, orderIdTail: string): Promise<Record<string, unknown>[]> {
    const result = await this.dynamo.doc.send(
      new QueryCommand({
        TableName: this.config.ordersTable,
        IndexName: ORIGIN_INDEX,
        KeyConditionExpression: "origin = :origin",
        ExpressionAttributeValues: { ":origin": originFor(store, orderIdTail) },
      }),
    );
    return result.Items ?? [];
  }

  /** SKU -> total quantity for the order as recorded in staging-orders-v2 (one ITEM# row per unit). */
  async getOrderSkuQuantities(store: Store, orderIdTail: string): Promise<Record<string, number>> {
    const rows = await this.getOrderRows(store, orderIdTail);
    return orderSkuQuantitiesFromRows(rows);
  }

  /** The shared internal order UUID (PK) used by both tables, resolved via staging-orders-v2. Null if not landed yet. */
  async getOrderPk(store: Store, orderIdTail: string): Promise<string | null> {
    const rows = await this.getOrderRows(store, orderIdTail);
    return orderPkFromRows(rows);
  }

  /**
   * The ORDER row's hold/payment/totals surface (TAA-50) — composed off
   * getOrderRows, same pattern as getOrderPk/getOrderSkuQuantities: no new
   * query. Null if the order hasn't landed yet.
   */
  async getOrderRecord(store: Store, orderIdTail: string): Promise<OrderRecord | null> {
    const rows = await this.getOrderRows(store, orderIdTail);
    return orderRecordFromRows(rows);
  }

  /**
   * ADDRESS#SHIPPING and ADDRESS#BILLING rows for an order (TAA-50) —
   * composed off getOrderRows, no new query.
   */
  async getAddressRows(store: Store, orderIdTail: string): Promise<AddressRow[]> {
    const rows = await this.getOrderRows(store, orderIdTail);
    return addressRowsFromRows(rows);
  }

  /**
   * ITEM# rows on staging-orders-v2 for an order (TAA-50) — composed off
   * getOrderRows, no new query. Sibling to getShipmentItemsByPk, which reads
   * the equivalent rows on staging-shipments.
   */
  async getOrderItemRows(store: Store, orderIdTail: string): Promise<OrderItemRow[]> {
    const rows = await this.getOrderRows(store, orderIdTail);
    return orderItemRowsFromRows(rows);
  }

  /**
   * `TRANSACTION#` rows for an order from staging-orders-v2 (TAA-48) —
   * chronological (see transactionRowsFromRows). Unlike getTransactionsByPk
   * (staging-shipments, needs its own query once the PK is known), this
   * needs no separate query at all: getOrderRows already fetches every row
   * for the order via origin_index, TRANSACTION# rows included — same
   * composition pattern as getOrderSkuQuantities/getOrderPk above. A caller
   * with an already-resolved PK but no store/orderIdTail has no way to have
   * gotten that PK without already holding this same row set, so there is
   * no "ByPk" sibling here the way there is for staging-shipments.
   */
  async getOrderTransactions(store: Store, orderIdTail: string): Promise<TransactionRow[]> {
    const rows = await this.getOrderRows(store, orderIdTail);
    return transactionRowsFromRows(rows);
  }

  /**
   * ITEM# rows for an order from staging-shipments, normalized with the
   * allocated store resolved from the sibling SHIPMENT# row. One entry per
   * unit. Empty = shipments not created yet OR the order hasn't landed in
   * staging-orders-v2 at all (so no PK to query with) — callers distinguish
   * by pipeline stage.
   */
  async getShipmentItems(store: Store, orderIdTail: string): Promise<ShipmentItem[]> {
    const pk = await this.getOrderPk(store, orderIdTail);
    if (!pk) {
      return [];
    }
    return this.getShipmentItemsByPk(pk);
  }

  /**
   * Same as getShipmentItems, but for a PK already resolved by the caller —
   * lets the composite orders_table+allocation poll (TAA-14 Phase A step 3)
   * resolve the PK once from rows it already fetched, instead of every
   * allocation tick re-querying staging-orders-v2 just to re-derive it.
   */
  async getShipmentItemsByPk(pk: string): Promise<ShipmentItem[]> {
    const rows = await this.queryShipmentRows(pk);

    const shipmentsById = new Map<string, Record<string, unknown>>();
    for (const row of rows) {
      const sk = String(row.SK ?? "");
      if (sk.startsWith("SHIPMENT#")) {
        shipmentsById.set(sk.slice("SHIPMENT#".length), row);
      }
    }

    const items: ShipmentItem[] = [];
    for (const row of rows) {
      const sk = String(row.SK ?? "");
      if (!sk.startsWith("ITEM#")) {
        continue; // shipment-level or transaction row, not an item row
      }
      const status = String(row.status ?? "");
      const shipmentId = row.shipmentId ? String(row.shipmentId) : null;
      let allocatedStore: string | null = null;
      if (status === UNDELIVERABLE) {
        allocatedStore = UNDELIVERABLE;
      } else if (shipmentId) {
        const shipment = shipmentsById.get(shipmentId);
        const value = shipment?.allocatedStore;
        allocatedStore = value ? String(value) : null;
      }
      items.push({
        sku: String(row.sku ?? ""),
        store: allocatedStore,
        status,
        rejectedStores: (row.rejectedStores as string[] | undefined) ?? [],
        shipmentItemId: sk,
        shipmentId,
        raw: row,
      });
    }
    return items;
  }

  /**
   * SHIPMENT# rows for an order, for a PK already resolved by the caller —
   * same shape of call as getShipmentItemsByPk (TAA-35 scope addition,
   * 2026-08-21). The row is already fetched by getShipmentItemsByPk on every
   * run; this is a separate entry point for callers that only need the
   * shipment-level fields (status/trackingNumber/carrier/pendingAction),
   * not the per-item view.
   */
  async getShipmentsByPk(pk: string): Promise<ShipmentSummary[]> {
    const rows = await this.queryShipmentRows(pk);
    return shipmentSummariesFromRows(rows);
  }

  /**
   * `TRANSACTION#` rows for an order, for a PK already resolved by the
   * caller (TAA-31 slice G) — same shape of call as getShipmentsByPk.
   * Promotes what `probe-reject.ts`'s ad hoc `dumpTransactionRows` already
   * queried directly (`dynamoReader.ts`'s public surface didn't expose these
   * rows before this) into a reusable, typed reader.
   */
  async getTransactionsByPk(pk: string): Promise<TransactionRow[]> {
    const rows = await this.queryShipmentRows(pk);
    return transactionRowsFromRows(rows);
  }

  private async queryShipmentRows(pk: string): Promise<Record<string, unknown>[]> {
    const result = await this.dynamo.doc.send(
      new QueryCommand({
        TableName: this.config.shipmentsTable,
        KeyConditionExpression: "PK = :pk",
        ExpressionAttributeValues: { ":pk": pk },
      }),
    );
    return result.Items ?? [];
  }
}

/** Summarizes normalized shipment items for assertions. Pure (no AWS access) so it's offline-testable. */
export function allocationSummary(items: ShipmentItem[]): AllocationSummary {
  const byStore: Record<string, string[]> = {};
  const skuUnits: Record<string, number> = {};
  let unallocated = 0;
  for (const item of items) {
    let store = item.store;
    if (store === null || store === "") {
      unallocated += 1;
      store = "(unallocated)";
    }
    byStore[store] = byStore[store] ?? [];
    byStore[store].push(item.sku);
    skuUnits[item.sku] = (skuUnits[item.sku] ?? 0) + 1;
  }
  return {
    totalUnits: items.length,
    byStore,
    skuUnits,
    unallocated,
    undeliverableKey: UNDELIVERABLE,
  };
}
